version: "3.8"

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    depends_on:
      - socket-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik:/traefik
    environment:
      SCALEWAY_API_TOKEN: /run/secrets/SCALEWAY_API_TOKEN
      SCALEWAY_PROJECT_ID: /run/secrets/SCALEWAY_PROJECT_ID
      DOMAIN: /run/secrets/domain
      TLD: /run/secrets/tld
    secrets:
      - SCALEWAY_API_TOKEN
      - SCALEWAY_PROJECT_ID
      - domain
      - tld
    networks:
      - proxy
    labels:
      - "traefik.enable=true"

      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      # redirect root to www
      - "traefik.http.routers.root.rule=host(`${DOMAIN}.${TLD}`)"
      - "traefik.http.routers.root.entrypoints=https"
      - "traefik.http.routers.root.middlewares=redirect-root-to-www"
      - "traefik.http.routers.root.tls=true"

      # middleware redirect root to www
      - "traefik.http.middlewares.redirect-root-to-www.redirectregex.regex=^https://${DOMAIN}\\.${TLD}/(.*)"
      - "traefik.http.middlewares.redirect-root-to-www.redirectregex.replacement=https://www.${DOMAIN}.${TLD}/$${1}"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
      
    configs:
      - source: traefik_yml
        target: ./traefik.yml
        
      - source: tls_yml
        target: ./rules/tls.yml
        
      - source: whitelist_yml
        target: ./rules/whitelist.yml   

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: traefik-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
    networks:
      - proxy
    labels:
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true

configs:
  traefik_yml:
    external: true
  tls_yml:
    external: true
  whitelist_yml:
    external: true
    
secrets:
  SCALEWAY_API_TOKEN:
    external: true
  SCALEWAY_PROJECT_ID:
    external: true
  domain:
    external: true
  tld:
    external: true
    
volumes:
  traefik:
    driver_opts:
      type: nfs
      o: addr=192.168.2.200
      device: :/mnt/shared/proxmox/traefik/
  
