entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false

  file:
    directory: /rules
    watch: true

certificatesResolvers:
  dns:
    acme:
      email: infrastructure@simplyepic.co.uk
      storage: ./letsencrypt/acme.json
      dnsChallenge:
        provider: scaleway
        delayBeforeCheck: 10

log:
  level: INFO
